// Record the narration of the explainer videos (sassi/ui/static/videos) with ElevenLabs text-to-speech.
//
//   ELEVENLABS_API_KEY=... node web/voice_videos.mjs              # every video: record what is missing
//   ELEVENLABS_API_KEY=... node web/voice_videos.mjs 01 02        # some videos
//   node web/voice_videos.mjs --dry                               # what would be recorded, and how many characters
//   options: --voice <voice id> --voice-name <name> --model <model id> --speed 1.1 --concurrency 2 --force
//
// One MP3 per beat (audio/NN/<hash>.mp3, 44.1 kHz 64 kb/s mono), named by the hash of the spoken text
// (SV.hash in player.js), and the manifest aNN.js: SV.AUDIO["NN"] = {voice, ..., beats: {<hash>: {f, d, m}}} with
// the clip's duration d (s) and the time of every [marker] of the beat m (s, from the character timings of the
// /with-timestamps endpoint).  A beat whose text is unchanged keeps its clip, so a re-run records only the
// edited sentences; clips no longer used are deleted.  A change of voice, model or settings re-records all.
// Neighbouring sentences go along as previous_text / next_text so that the intonation flows across beats.
// The key is read from ELEVENLABS_API_KEY (or --key-file FILE) and never printed or written anywhere.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import {fileURLToPath} from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const VIDEOS = path.resolve(HERE, "../sassi/ui/static/videos");
const args = process.argv.slice(2);
const opt = (name, dflt) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : dflt; };
const VALUED = ["--voice", "--voice-name", "--model", "--speed", "--concurrency", "--key-file"];
const ids = args.filter((a, i) => /^\d\d$/.test(a) && !VALUED.includes(args[i - 1]));
const DRY = args.includes("--dry"), FORCE = args.includes("--force");
const VOICE_ID = opt("--voice", "XrExE9yKIg1WjnnlVkGX");          // "Matilda": knowledgeable, upbeat educator
const VOICE_NAME = opt("--voice-name", VOICE_ID === "XrExE9yKIg1WjnnlVkGX" ? "Matilda" : VOICE_ID);
const MODEL = opt("--model", "eleven_multilingual_v2");
const SETTINGS = {stability: 0.45, similarity_boost: 0.8, style: 0.15, use_speaker_boost: true, speed: +opt("--speed", "1.1")};
const FORMAT = "mp3_44100_64";
const SIG = JSON.stringify({VOICE_ID, MODEL, SETTINGS, FORMAT});
const CONC = +opt("--concurrency", "2");
let KEY = process.env.ELEVENLABS_API_KEY || "";
if (opt("--key-file")) KEY = fs.readFileSync(opt("--key-file"), "utf8").trim();

// ------------------------------------------------------------------ the videos' narration (as the player sees it)
function loadVideos(list) {
  const fake = () => ({style: {}, classList: {add() {}, remove() {}, toggle() {}}, appendChild() {}, setAttribute() {}, addEventListener() {}, textContent: ""});
  const ctx = {console, Math, JSON, Date, Array, Object, String, Number, Set, Map, RegExp, Error, Float64Array, Int32Array, Uint8Array, parseFloat, parseInt, isFinite, isNaN};
  ctx.window = ctx; ctx.globalThis = ctx;
  ctx.document = {createElement: fake, createElementNS: fake, head: fake(), body: fake(), readyState: "complete", addEventListener() {}};
  ctx.location = {search: "", hash: ""};
  vm.createContext(ctx);
  const run = (f) => vm.runInContext(fs.readFileSync(path.join(VIDEOS, f), "utf8"), ctx, {filename: f});
  run("../figures.js");
  run("player.js");
  ctx.SV.catalog = [];
  run("kit.js");
  const out = [];
  for (const id of list) {
    const before = ctx.SV.catalog.length;
    if (fs.existsSync(path.join(VIDEOS, `d${id}.js`))) run(`d${id}.js`);
    run(`v${id}.js`);
    const def = ctx.SV.catalog[before];
    const pron = (def.pron || []).concat(ctx.SV.PRON);
    const beats = [];
    def.scenes.forEach((sc) => sc.beats.forEach((b) => {
      const p = ctx.SV.parseSay(b.say, pron);
      const text = p.spoken.trim();
      if (!text) return;
      const lead = p.spoken.length - p.spoken.trimStart().length;
      beats.push({text, h: ctx.SV.hash(text), marks: p.marks.map((m) => ({name: m.name, at: Math.max(0, m.at - lead)}))});
    }));
    out.push({id, beats});
  }
  return out;
}

function readManifest(id) {
  const f = path.join(VIDEOS, `a${id}.js`);
  if (!fs.existsSync(f)) return null;
  const t = fs.readFileSync(f, "utf8");
  const i = t.indexOf(`SV.AUDIO["${id}"] = `);
  if (i < 0) return null;
  return JSON.parse(t.slice(i + `SV.AUDIO["${id}"] = `.length, t.lastIndexOf("};") + 1));
}
function writeManifest(id, man) {
  const beats = Object.keys(man.beats).sort().map((h) => `${JSON.stringify(h)}:${JSON.stringify(man.beats[h])}`).join(",\n");
  const head = JSON.stringify({voice: man.voice, voiceId: man.voiceId, model: man.model, sig: man.sig});
  const text = `/* ElevenLabs narration of explainer video ${id} (generated by web/voice_videos.mjs; do not edit). */\n"use strict";\n`
    + `(window.SV = window.SV || {}).AUDIO = window.SV.AUDIO || {};\n`
    + `SV.AUDIO["${id}"] = ${head.slice(0, -1)},"beats":{\n${beats}}};\n`;
  fs.writeFileSync(path.join(VIDEOS, `a${id}.js`), text);
}
/** Make NN.html load aNN.js (before vNN.js). */
function linkManifest(id) {
  const f = path.join(VIDEOS, `${id}.html`);
  let t = fs.readFileSync(f, "utf8");
  if (t.includes(`src="a${id}.js"`)) return;
  t = t.replace(`<script src="v${id}.js"></script>`, `<script src="a${id}.js"></script>\n<script src="v${id}.js"></script>`);
  fs.writeFileSync(f, t);
}

// ------------------------------------------------------------------ ElevenLabs
class StopError extends Error {}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function tts(text, prev, next) {
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}/with-timestamps?output_format=${FORMAT}`;
  const body = {text, model_id: MODEL, voice_settings: SETTINGS};
  if (prev) body.previous_text = prev;
  if (next) body.next_text = next;
  for (let attempt = 0; ; attempt++) {
    let r;
    try {
      r = await fetch(url, {method: "POST", headers: {"xi-api-key": KEY, "Content-Type": "application/json", Accept: "application/json"}, body: JSON.stringify(body)});
    } catch (e) {
      if (attempt < 4) { await sleep(2000 * (attempt + 1)); continue; }
      throw e;
    }
    if (r.ok) return {json: await r.json(), cost: +(r.headers.get("character-cost") || 0)};
    const detail = await r.text();
    if ((r.status === 429 || r.status >= 500) && attempt < 6) { await sleep(1500 * 2 ** attempt); continue; }
    let msg = detail;
    try { const d = JSON.parse(detail).detail; msg = typeof d === "string" ? d : `${d.status || d.code || ""}: ${d.message || ""}`; } catch (e) { /* raw */ }
    throw new StopError(`ElevenLabs answered ${r.status}: ${msg.slice(0, 300)}`);
  }
}
/** Marker times (s) from the character timings; a marker on a space takes the next character's time. */
function markTimes(marks, text, al) {
  const m = {};
  const n = al.characters.length;
  const starts = al.character_start_times_seconds;
  for (const mk of marks) {
    let i = Math.min(mk.at, text.length - 1);
    while (i < text.length - 1 && /\s/.test(text[i])) i++;
    if (n !== text.length) i = Math.round((i / Math.max(1, text.length)) * (n - 1));   // normalised text: proportional
    m[mk.name] = Math.round(starts[Math.max(0, Math.min(n - 1, i))] * 1000) / 1000;
  }
  return m;
}

// ------------------------------------------------------------------ main
const list = ids.length ? ids : fs.readdirSync(VIDEOS).filter((f) => /^v\d\d\.js$/.test(f)).map((f) => f.slice(1, 3)).sort();
const videos = loadVideos(list);
let totalChars = 0, totalCost = 0, made = 0, failed = null;
for (const v of videos) {
  let man = readManifest(v.id);
  if (!man || man.sig !== SIG || FORCE) man = {voice: VOICE_NAME, voiceId: VOICE_ID, model: MODEL, sig: SIG, beats: man && man.sig === SIG && !FORCE ? man.beats : {}};
  const dir = path.join(VIDEOS, "audio", v.id);
  const todo = v.beats.map((b, i) => ({b, i})).filter(({b}) => !man.beats[b.h] || !fs.existsSync(path.join(VIDEOS, man.beats[b.h].f)));
  const chars = todo.reduce((a, {b}) => a + b.text.length, 0);
  totalChars += chars;
  console.log(`${v.id}: ${v.beats.length} beats, ${todo.length} to record (${chars} characters)`);
  if (DRY || !todo.length) { if (!DRY) finish(v, man); continue; }
  if (!KEY) { console.error("set ELEVENLABS_API_KEY (or --key-file FILE)"); process.exit(2); }
  fs.mkdirSync(dir, {recursive: true});
  let next = 0;
  const worker = async () => {
    while (next < todo.length && !failed) {
      const {b, i} = todo[next++];
      const prev = v.beats[i - 1] ? v.beats[i - 1].text : "", nxt = v.beats[i + 1] ? v.beats[i + 1].text : "";
      try {
        const {json, cost} = await tts(b.text, prev, nxt);
        const al = json.alignment || json.normalized_alignment;
        const rel = `audio/${v.id}/${b.h}.mp3`;
        fs.writeFileSync(path.join(VIDEOS, rel), Buffer.from(json.audio_base64, "base64"));
        const ends = al.character_end_times_seconds;
        man.beats[b.h] = {f: rel, d: Math.round((ends[ends.length - 1] + 0.12) * 1000) / 1000, m: markTimes(b.marks, b.text, al)};
        totalCost += cost;
        made++;
        if (made % 10 === 0) { writeManifest(v.id, man); process.stdout.write(`  ${made} clips\n`); }
      } catch (e) {
        failed = e;
      }
    }
  };
  await Promise.all(Array.from({length: Math.max(1, CONC)}, worker));
  finish(v, man);
  if (failed) break;
}
function finish(v, man) {
  // keep only the clips of the current text; delete unused files
  const used = new Set(v.beats.map((b) => b.h));
  for (const h of Object.keys(man.beats)) if (!used.has(h)) delete man.beats[h];
  const dir = path.join(VIDEOS, "audio", v.id);
  if (fs.existsSync(dir)) {
    const keep = new Set(Object.values(man.beats).map((c) => path.basename(c.f)));
    for (const f of fs.readdirSync(dir)) if (!keep.has(f)) fs.rmSync(path.join(dir, f));
  }
  if (Object.keys(man.beats).length) { writeManifest(v.id, man); linkManifest(v.id); }
}
console.log(`${DRY ? "would record" : "recorded"} ${DRY ? totalChars : made} ${DRY ? "characters" : "clips"}${DRY ? "" : `, character cost ${totalCost}`}`);
if (failed) { console.error(failed instanceof StopError ? failed.message : String(failed)); console.error("stopped; what was recorded is kept, run again to continue"); process.exit(1); }
